#!/bin/sh

sed -nr '
  /^(version|name) = "([^" ]*)"/{ 
    s//\2 / 
    H
  }
  /^\[.*/{ 
    s///
    x
    s/ \n/==/
    s/\n//g
    /dataclasses/s/.*/&; python_version < "3.7"/
    /./p
  }' poetry.lock
