#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

git diff --name-only --cached svgs | {
  while read -r svg_file; do
    cp -fv $svg_file ${svg_file%.svg}-prev.svg
  done  
}
